version: '3'
services:

  web:
    image: nginx:1.17
    restart: unless-stopped
    volumes:
      - ../:/var/www:delegated
      - ./local.web.default.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - db
    ports:
      - 8000:80

  app:
    image: engageinteractive/base-php:7.4
    restart: unless-stopped
    volumes:
      - ../:/var/www:delegated
      - ./local.app.php.ini:/usr/local/etc/php/php.ini:delegated
      - ~/.composer/docker-cache/:/root/.composer:cached
    depends_on:
      - db
    working_dir: /var/www
    environment:
      - "COMPOSER_ALLOW_SUPERUSER=true"
      - "DBUS_SESSION_BUS_ADDRESS=/dev/null"

  db:
    image: mariadb:10.3
    restart: unless-stopped
    volumes:
      - ../docker/local.db.schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - database:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - 13306:3306

  build:
    image: node:12
    volumes:
      - ../:/app:delegated
      - ~/.yarn/docker-cache/:/root/.yarn:cached
    environment:
      - "YARN_CACHE_FOLDER=/root/.yarn"
    working_dir: /app
    ports:
      - 5757:5757

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

volumes:
  database:
